import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bath, BedDouble, Building2, CheckCircle2, ChevronRight, Compass, Home, KeyRound, MapPin, MessageCircle, Mountain, Search, Send, ShieldCheck, Sparkles, Trees, UsersRound } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { CTASection, PropertyGrid, SectionTitle, ServicesGrid, trustIcons, trustItems } from "@/components/content";
import { areas, areaSlugs, images, properties, whatsappUrl } from "@/data/site";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Real Estate in Solan | Solan Estates" },
      { name: "description", content: "Explore properties for sale and rent with trusted real estate services in Solan, Himachal Pradesh, including Kandaghat, Barog and nearby areas." },
      { property: "og:title", content: "Trusted Real Estate Services in Solan" },
      { property: "og:description", content: "Find houses, flats, plots and commercial property across Solan with professional local guidance." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/" },
      { name: "twitter:card", content: "summary_large_image" },
    ], links: [{ rel: "canonical", href: "/" }],
    scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "RealEstateAgent", name: "Solan Estates", description: "Demonstration real estate agency serving Solan and nearby Himachal Pradesh areas.", areaServed: ["Solan", "Kandaghat", "Kumarhatti", "Dharampur", "Barog", "Chambaghat", "Saproon", "Shilli", "Nauni", "Oachghat"] }) }],
  }), component: HomePage,
});

const categories = [
  [Home, "Houses for Sale", "/houses-for-sale-in-solan", images.home], [Building2, "Commercial Properties", "/commercial-property-in-solan", images.commercial],
  [Sparkles, "Villas", "/properties-for-sale", images.hero], [Building2, "Flats & Apartments", "/flats-for-sale-in-solan", images.home],
  [Trees, "Land & Plots", "/plots-for-sale-in-solan", images.plot], [KeyRound, "Rental Properties", "/properties-for-rent", images.commercial],
  [Mountain, "Mountain View Properties", "/properties", images.hero], [Compass, "Investment Properties", "/real-estate-in-solan", images.plot],
] as const;

const faqs = [
  ["Which are the best areas to buy property in Solan?", "The right area depends on your commute, lifestyle and property goals. Central Solan and Saproon suit everyday access, while Kandaghat, Barog and Shilli may appeal to buyers seeking quieter surroundings and mountain views."],
  ["How can I find property for sale in Solan?", "Start with a clear budget, preferred property type and location. A local consultant can then shortlist relevant houses, flats, plots or commercial properties and arrange visits."],
  ["Do you help with property rentals in Solan?", "Yes. Rental assistance can cover family homes, flats, offices, shops and other commercial spaces across Solan and nearby areas."],
  ["Can I buy residential plots in Solan?", "Residential plots are available in and around Solan. Buyers should assess access, slope, utilities, title documents and applicable planning permissions before deciding."],
  ["Do you deal in commercial properties?", "Yes. Commercial assistance can include shops, offices, road-facing spaces and buildings for purchase, rent or investment."],
  ["Can you help me sell my property in Solan?", "Yes. A property consultant can help position your property, organize information, connect with suitable buyers and coordinate viewings."],
  ["What types of properties are available in Solan?", "The market includes independent houses, villas, flats, apartments, residential plots, land, shops, offices and rental properties."],
  ["How can I contact a property dealer in Solan?", "Use the enquiry form or WhatsApp link on this demonstration website. Replace the placeholder contact details with the agency’s verified information before publishing."],
] as const;

function SearchPanel() { const [tab, setTab] = useState("Buy"); const [searched, setSearched] = useState(false); return <div className="relative z-20 mx-auto -mt-10 w-[min(92%,72rem)] rounded-md border border-border bg-background p-3 shadow-xl md:p-6"><div className="flex gap-1 border-b border-border">{["Buy", "Rent", "Sell"].map(x => <button key={x} onClick={() => { setTab(x); setSearched(false); }} className={`px-5 pb-3 text-sm font-bold transition-colors ${tab === x ? "border-b-2 border-primary text-primary" : "text-muted-foreground"}`}>{x}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-[1.2fr_1.2fr_1fr_.8fr_auto]">{[["Property Type", ["House", "Villa", "Flat", "Apartment", "Plot", "Land", "Commercial Property", "Office", "Shop"]], ["Location", areas.map(a => a[0])], ["Budget", ["Under ₹50 Lakh", "₹50 Lakh – ₹1 Cr", "₹1 Cr – ₹2 Cr", "Above ₹2 Cr"]], ["Bedrooms", ["1+", "2+", "3+", "4+"]]].map(([label, options]) => <label key={label as string} className="grid gap-2 text-[0.65rem] font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}<select className="h-12 rounded-sm border border-input bg-background px-3 text-sm font-medium text-foreground outline-none focus:ring-2 focus:ring-ring"><option>{label === "Location" ? "All Solan Areas" : `Any ${label}`}</option>{(options as readonly string[]).map(o => <option key={o}>{o}</option>)}</select></label>)}<Button className="self-end" onClick={() => setSearched(true)}><Search /> Search {tab === "Sell" ? "Guidance" : "Properties"}</Button></div>{searched && <p role="status" className="mt-4 flex items-center gap-2 text-sm text-primary"><CheckCircle2 className="size-4" /> Showing relevant sample options. Contact us for a tailored shortlist.</p>}</div>; }

function HomePage() { const [sent, setSent] = useState(false); const submit = (e: FormEvent) => { e.preventDefault(); setSent(true); }; return <>
  <section className="relative min-h-[760px] overflow-hidden bg-primary text-primary-foreground"><img src={images.hero} alt="Luxury mountain-view villa in Solan, Himachal Pradesh" width={1920} height={1080} fetchPriority="high" className="absolute inset-0 size-full object-cover motion-safe:animate-[heroZoom_18s_ease-out_forwards]" /><div className="image-shade absolute inset-0" /><div className="container-site relative z-10 flex min-h-[760px] items-end pb-28 pt-36"><div className="max-w-3xl animate-fade-in"><p className="eyebrow">Trusted local property guidance</p><h1 className="mt-5 text-5xl font-semibold leading-[0.92] sm:text-6xl lg:text-8xl">Real Estate Services in Solan, Himachal Pradesh</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/80">Find your perfect property in Solan. Buy, sell, rent and invest in residential and commercial properties with trusted local professionals.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="gold" size="lg"><Link to="/properties">Explore Properties <ArrowRight /></Link></Button><Button asChild variant="light" size="lg"><Link to="/contact">Contact Us</Link></Button><Button asChild variant="light" size="lg"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> Chat on WhatsApp</a></Button></div></div></div><aside className="absolute bottom-16 right-[max(2rem,calc((100%-76rem)/2))] hidden w-72 animate-[floatCard_5s_ease-in-out_infinite] border border-primary-foreground/20 bg-background/95 p-5 text-foreground shadow-xl backdrop-blur md:block"><p className="text-[0.65rem] font-bold uppercase tracking-[0.16em] text-highlight">Sample spotlight</p><h2 className="mt-2 text-2xl font-semibold">{properties[0].title}</h2><p className="mt-1 text-xs text-muted-foreground">{properties[0].location}</p><div className="mt-4 flex gap-4 text-xs font-semibold"><span className="flex gap-1"><BedDouble className="size-4" />3 Bed</span><span className="flex gap-1"><Bath className="size-4" />3 Bath</span></div></aside>
  </section><SearchPanel />
  <section className="section-space section-reveal"><div className="container-site"><SectionTitle eyebrow="Curated opportunities" title="Featured Properties in Solan" copy="Explore a representative mix of residential property, mountain-view land and commercial space. All listings below are sample data for this demonstration." /><PropertyGrid /></div></section>
  <section className="section-space bg-surface"><div className="container-site"><SectionTitle eyebrow="How we can help" title="Our Real Estate Services" copy="Practical support for buying, selling, renting and property investment across Solan and surrounding Himachal areas." /><ServicesGrid /></div></section>
  <section className="section-space section-reveal"><div className="container-site grid items-center gap-14 lg:grid-cols-2"><div><SectionTitle eyebrow="Local insight, honest support" title="Why Choose Our Real Estate Services in Solan?" copy="Property decisions benefit from local context, careful comparison and clear communication." /><div className="grid gap-3 sm:grid-cols-2">{trustItems.map((x, i) => { const Icon = trustIcons[i] ?? ShieldCheck; return <div key={x} className="flex items-center gap-3 border-b border-border py-4 text-sm font-semibold"><Icon className="size-5 text-highlight" />{x}</div>; })}</div></div><div className="relative"><img src={images.home} alt="Premium family home overlooking the hills near Solan" loading="lazy" width={1400} height={1000} className="aspect-[4/5] w-full object-cover" /><div className="absolute -bottom-6 -left-4 bg-primary p-6 text-primary-foreground shadow-xl md:-left-8"><p className="font-display text-4xl font-semibold">10+</p><p className="text-xs uppercase tracking-[0.14em] text-primary-foreground/70">Local areas covered</p></div></div></div></section>
  <section className="section-space bg-muted"><div className="container-site"><SectionTitle eyebrow="Neighbourhood guide" title="Properties Across Solan & Nearby Areas" copy="Compare established neighbourhoods, transport corridors and quieter hillside settings before choosing where to focus your search." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{areas.map(([name, copy], i) => <Link key={name} to={areaSlugs[name] ? `/locations/${areaSlugs[name]}` as "/locations/solan" : "/locations"} className="group overflow-hidden rounded-md bg-card shadow-sm"><div className="aspect-[4/3] overflow-hidden"><img src={[images.hero, images.plot, images.home, images.commercial][i % 4]} alt={`Property landscape in ${name}, Himachal Pradesh`} loading="lazy" width={1400} height={1000} className="size-full object-cover transition-transform duration-700 group-hover:scale-105" /></div><div className="p-5"><h3 className="text-xl font-semibold">Real Estate in {name}</h3><p className="mt-2 line-clamp-3 text-xs leading-5 text-muted-foreground">{copy}</p><span className="mt-4 flex items-center gap-1 text-xs font-bold text-primary">Explore area <ChevronRight className="size-3" /></span></div></Link>)}</div></div></section>
  <section className="section-space"><div className="container-site"><SectionTitle eyebrow="Browse by lifestyle" title="Find Properties That Match Your Needs" align="center" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(([Icon, title, to, image]) => <Link key={title} to={to} className="group relative aspect-[4/5] overflow-hidden rounded-md bg-primary"><img src={image} alt={`${title} in Solan`} loading="lazy" width={1400} height={1000} className="size-full object-cover opacity-80 transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-primary via-primary/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-primary-foreground"><Icon className="size-6 text-highlight" /><h3 className="mt-3 text-2xl font-semibold">{title}</h3></div></Link>)}</div></div></section>
  <section className="section-space bg-primary text-primary-foreground"><div className="container-site grid gap-16 lg:grid-cols-[1fr_1.2fr]"><div><p className="eyebrow">About Solan Estates</p><h2 className="mt-4 text-5xl font-semibold leading-none">Your Trusted Real Estate Partner in Solan</h2></div><div><p className="text-lg leading-8 text-primary-foreground/75">We help buyers, sellers, landlords and investors understand suitable property options across Solan, Kandaghat, Kumarhatti, Dharampur, Barog and neighbouring areas. Our demonstration approach is built around local knowledge, transparency, careful property matching and long-term relationships.</p><div className="mt-10 grid grid-cols-2 gap-px bg-primary-foreground/15 sm:grid-cols-4">{[["100+", "Properties assisted"], ["50+", "Happy clients"], ["10+", "Local areas"], ["5+", "Years' experience"]].map(([n, l]) => <div key={l} className="bg-primary p-4"><p className="font-display text-4xl font-semibold text-highlight">{n}</p><p className="mt-1 text-[0.65rem] uppercase tracking-wider text-primary-foreground/60">{l}*</p></div>)}</div><p className="mt-4 text-xs text-primary-foreground/45">* Demonstration statistics; replace with verified business figures before publishing.</p></div></div></section>
  <section className="section-space"><div className="container-site"><SectionTitle eyebrow="A clear process" title="Finding Your Property Is Simple" align="center" /><div className="relative grid gap-5 md:grid-cols-4">{[["01", "Tell Us Your Requirement", "Share your budget, preferred area and property type."], ["02", "Explore Suitable Properties", "Review a focused shortlist rather than unrelated options."], ["03", "Schedule a Property Visit", "Walk through promising choices and compare them carefully."], ["04", "Complete Your Deal", "Move forward with clear coordination and professional support."]].map(([n, t, c]) => <article key={n} className="relative border-t-2 border-highlight bg-surface p-6"><span className="font-display text-5xl text-primary/20">{n}</span><h3 className="mt-7 text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{c}</p></article>)}</div></div></section>
  <section className="section-space bg-surface"><div className="container-site grid items-center gap-14 lg:grid-cols-2"><img src={images.plot} alt="Residential land and mountain views near Kandaghat, Solan" loading="lazy" width={1400} height={1000} className="aspect-[4/3] w-full object-cover" /><div><SectionTitle eyebrow="Considered opportunity" title="Invest in Solan Real Estate" copy="Solan’s position within Himachal Pradesh may interest buyers seeking residential use, hospitality possibilities or long-term land ownership." /><ul className="grid gap-3 sm:grid-cols-2">{["Residential demand", "Chandigarh–Shimla access", "Tourism and hospitality", "Ongoing development", "Land and plot choices", "Diverse local areas"].map(x => <li key={x} className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="size-4 text-highlight" />{x}</li>)}</ul><p className="mt-6 text-sm leading-6 text-muted-foreground">Property suitability, permissions and returns vary. Independent legal and financial checks are essential; no outcome is guaranteed.</p><Button asChild className="mt-7"><Link to="/contact">Talk to a Property Consultant</Link></Button></div></div></section>
  <section className="section-space"><div className="container-site"><SectionTitle eyebrow="Demo client stories" title="Thoughtful service, remembered" copy="The reviews below are fictional examples included only to demonstrate the presentation style." /><div className="grid gap-5 md:grid-cols-3">{[["Rajesh Sharma", "They understood our requirements and showed us suitable options in Solan without wasting our time."], ["Neha Verma", "Clear communication and patient guidance made comparing a flat and an independent home much easier."], ["Amit Sood", "The local area insights were especially useful while reviewing plots around Kandaghat and Barog."]].map(([name, quote]) => <figure key={name} className="border border-border bg-card p-7 shadow-sm"><p className="text-highlight" aria-label="5 out of 5 stars">★★★★★</p><blockquote className="mt-5 font-display text-2xl leading-8">“{quote}”</blockquote><figcaption className="mt-6 text-sm font-bold">— {name} <span className="font-normal text-muted-foreground">(demo)</span></figcaption></figure>)}</div></div></section>
  <CTASection />
  <section className="section-space"><div className="container-site grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><SectionTitle eyebrow="Helpful answers" title="Frequently Asked Questions" copy="Straightforward guidance for common questions about property in Solan." /><Accordion type="single" collapsible>{faqs.map(([q, a], i) => <AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger className="py-6 text-base">{q}</AccordionTrigger><AccordionContent className="max-w-3xl text-sm leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  <section className="section-space bg-surface"><div className="container-site grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><SectionTitle eyebrow="Start a conversation" title="Let's Find Your Next Property" copy="Tell us what you are looking for and this demonstration enquiry will show a confirmation on screen." /><div className="space-y-3 text-sm text-muted-foreground"><p className="flex gap-3"><MapPin className="size-5 text-highlight" />Office: Solan, Himachal Pradesh (placeholder)</p><p className="flex gap-3"><MessageCircle className="size-5 text-highlight" />WhatsApp: Demo placeholder</p><p className="flex gap-3"><Building2 className="size-5 text-highlight" />Email: enquiries@example.com</p></div></div><form onSubmit={submit} className="grid gap-4 rounded-md border border-border bg-background p-6 shadow-sm sm:grid-cols-2">{[["Full Name", "text"], ["Phone Number", "tel"], ["Email", "email"], ["Looking For", "text"], ["Preferred Location", "text"], ["Budget", "text"]].map(([label, type]) => <label key={label} className="grid gap-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}<input required={label === "Full Name" || label === "Phone Number"} type={type} placeholder={label} className="h-12 rounded-sm border border-input bg-background px-4 font-normal normal-case tracking-normal text-foreground outline-none focus:ring-2 focus:ring-ring" /></label>)}<label className="grid gap-2 text-xs font-bold uppercase tracking-wider text-muted-foreground sm:col-span-2">Message<textarea placeholder="Tell us about your property requirement" className="min-h-28 rounded-sm border border-input bg-background p-4 font-normal normal-case tracking-normal text-foreground outline-none focus:ring-2 focus:ring-ring" /></label><div className="flex flex-wrap gap-3 sm:col-span-2"><Button type="submit"><Send /> Send Enquiry</Button><Button asChild variant="outline"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Us</a></Button></div>{sent && <p role="status" className="sm:col-span-2 text-sm text-primary">Thank you. This is a demo form, so no information was sent.</p>}</form></div></section>
</>; }
