import { Link } from "@tanstack/react-router";
import { ArrowRight, Bath, BedDouble, Building2, CheckCircle2, Compass, Handshake, Home, KeyRound, MapPin, MessageCircle, Mountain, Ruler, Search, ShieldCheck, Store, Trees, UsersRound } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { images, properties, whatsappUrl } from "@/data/site";

export function SectionTitle({ eyebrow, title, copy, align = "left" }: { eyebrow: string; title: string; copy?: string; align?: "left" | "center" }) { return <div className={`mb-10 ${align === "center" ? "mx-auto max-w-3xl text-center" : "max-w-2xl"}`}><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 text-4xl font-semibold leading-[1.05] text-foreground md:text-5xl">{title}</h2>{copy && <p className="mt-5 text-base leading-7 text-muted-foreground">{copy}</p>}</div>; }

export function Breadcrumbs({ items }: { items: { label: string; to?: string }[] }) { return <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-primary-foreground/70"><Link to="/" className="hover:text-primary-foreground">Home</Link>{items.map((item) => <span key={item.label} className="flex items-center gap-2"><span>/</span>{item.to ? <Link to={item.to} className="hover:text-primary-foreground">{item.label}</Link> : <span>{item.label}</span>}</span>)}</nav>; }

export function PageHero({ title, eyebrow, intro, image = images.hero }: { title: string; eyebrow: string; intro: string; image?: string }) { return <section className="relative flex min-h-[510px] items-end overflow-hidden bg-primary pt-32 text-primary-foreground"><img src={image} alt="Hillside property and mountain landscape in Solan, Himachal Pradesh" className="absolute inset-0 size-full object-cover" width={1920} height={1080} /><div className="image-shade absolute inset-0" /><div className="container-site relative z-10 pb-16"><Breadcrumbs items={[{ label: title }]} /><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-[0.95] md:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-primary-foreground/80 md:text-lg">{intro}</p></div></section>; }

export function PropertyCard({ property = properties[0] }: { property?: (typeof properties)[number] }) { return <article className="group overflow-hidden rounded-md border border-border bg-card shadow-sm transition-all duration-500 hover:-translate-y-2 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden"><img src={property.image} alt={`${property.title} sample property in ${property.location}`} loading="lazy" width={1400} height={1000} className="size-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute left-4 top-4 flex gap-2"><span className="rounded-sm bg-primary px-3 py-1 text-[0.65rem] font-bold uppercase tracking-wider text-primary-foreground">{property.status}</span><span className="rounded-sm bg-background/90 px-3 py-1 text-[0.65rem] font-bold uppercase tracking-wider text-foreground backdrop-blur">Sample</span></div></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-highlight">{property.type}</p><h3 className="mt-1 text-2xl font-semibold">{property.title}</h3></div><p className="shrink-0 font-display text-xl font-bold text-primary">{property.price}</p></div><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4 text-highlight" />{property.location}</p><div className="my-4 flex flex-wrap gap-4 border-y border-border py-3 text-xs font-semibold text-muted-foreground">{property.beds > 0 && <span className="flex items-center gap-1"><BedDouble className="size-4" />{property.beds} Beds</span>}{property.baths > 0 && <span className="flex items-center gap-1"><Bath className="size-4" />{property.baths} Baths</span>}<span className="flex items-center gap-1"><Ruler className="size-4" />{property.area}</span></div><p className="line-clamp-2 text-sm leading-6 text-muted-foreground">{property.description}</p><div className="mt-5 flex gap-2"><Button asChild size="sm"><Link to="/properties">View Details <ArrowRight /></Link></Button><Button asChild variant="outline" size="icon"><a href={whatsappUrl} target="_blank" rel="noreferrer" aria-label={`Ask about ${property.title} on WhatsApp`}><MessageCircle /></a></Button></div></div></article>; }

export function PropertyGrid({ count = 4 }: { count?: number }) { return <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{properties.slice(0, count).map((p) => <PropertyCard key={p.title} property={p} />)}</div>; }

export const services = [
  [Home, "Property Buying", "Find residential and commercial properties that fit your location, budget and lifestyle."],
  [Handshake, "Property Selling", "Present and market your property with professional local support at every step."],
  [KeyRound, "Property Rental", "Explore suitable houses, flats and commercial property for rent across Solan."],
  [Trees, "Land & Plot Deals", "Assess residential plots, land access, surroundings and long-term suitability."],
  [Store, "Commercial Properties", "Discover shops, offices, buildings and practical investment opportunities."],
  [Compass, "Property Consultation", "Make considered buying, selling and property investment decisions."],
] as const;

export function ServicesGrid() { return <div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{services.map(([Icon, title, copy], i) => <article key={title} className="group bg-background p-8 transition-colors hover:bg-surface"><span className="grid size-12 place-items-center rounded-full border border-primary/20 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground"><Icon className="size-5" /></span><p className="mt-8 text-xs font-bold text-highlight">0{i + 1}</p><h3 className="mt-2 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div>; }

export function CTASection({ title = "Looking for Property in Solan?", copy = "Whether you want to buy, sell, rent or invest, speak with a local property consultant about the right next step." }: { title?: string; copy?: string }) { return <section className="relative overflow-hidden bg-primary py-24 text-primary-foreground"><img src={images.hero} alt="Mountain-view home in Solan" loading="lazy" width={1920} height={1080} className="absolute inset-0 size-full object-cover opacity-30" /><div className="absolute inset-0 bg-primary/70" /><div className="container-site relative z-10 text-center"><p className="eyebrow">A considered next move</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl font-semibold md:text-6xl">{title}</h2><p className="mx-auto mt-5 max-w-2xl text-primary-foreground/75">{copy}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild variant="gold" size="lg"><Link to="/properties">View Properties</Link></Button><Button asChild variant="light" size="lg"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Us</a></Button></div></div></section>; }

export function EditorialPage({ title, eyebrow, intro, sections, image = images.hero, showProperties = true }: { title: string; eyebrow: string; intro: string; sections: { title: string; body: string }[]; image?: string; showProperties?: boolean }) { return <><PageHero title={title} eyebrow={eyebrow} intro={intro} image={image} /><section className="section-space"><div className="container-site grid gap-14 lg:grid-cols-[1fr_0.65fr]"><div>{sections.map((section, index) => <article key={section.title} className={`${index ? "mt-10 border-t border-border pt-10" : ""}`}><h2 className="text-3xl font-semibold md:text-4xl">{section.title}</h2><p className="mt-4 text-base leading-8 text-muted-foreground">{section.body}</p></article>)}</div><aside className="self-start bg-surface p-8 lg:sticky lg:top-28"><ShieldCheck className="size-8 text-primary" /><h2 className="mt-5 text-3xl font-semibold">Local guidance, clearly explained</h2><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{["Requirement-led property shortlisting", "Support for visits and comparisons", "Transparent, professional communication", "Residential and commercial assistance"].map(x => <li key={x} className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-highlight" />{x}</li>)}</ul><Button asChild className="mt-7 w-full"><Link to="/contact">Discuss Your Requirement</Link></Button></aside></div></section>{showProperties && <section className="section-space bg-muted"><div className="container-site"><SectionTitle eyebrow="Sample portfolio" title="A glimpse of properties across Solan" copy="These demonstration listings show how houses, plots, rentals and commercial opportunities can be presented." /><PropertyGrid /></div></section>}<CTASection /></>; }

export const trustItems = ["Local Solan market knowledge", "Verified property options", "Transparent deals", "Professional guidance", "Personalized property search", "End-to-end assistance", "Trusted local service", "Investment guidance"];
export const trustIcons = [MapPin, ShieldCheck, Handshake, UsersRound, Search, CheckCircle2, Building2, Mountain] as const;
export function InfoCard({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <div className="border border-border bg-card p-6 shadow-sm">{icon}<h3 className="mt-5 text-2xl font-semibold">{title}</h3><div className="mt-3 text-sm leading-6 text-muted-foreground">{children}</div></div>; }
